#!/bin/bash
# Copyright 2016, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# (c) 2016, Kevin Carter <kevin.carter@rackspace.com>

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
else
    set -v
fi

set -eu
set -o pipefail

source /etc/os-release 2>/dev/null
export DISTRO_ID="${ID}"
export DISTRO_NAME="${NAME}"
export DISTRO_VERSION_ID="${VERSION_ID}"

function debian_deploy {
  # Package update and install
  apt-get update
  DEBIAN_FRONTEND="noninteractive" apt-get -y install bridge-utils vlan ifenslave

  if ! grep -qw "^bonding" /etc/modules; then
    echo "bonding" >> /etc/modules
  fi

}

function deploy_centos {
  yum -y install bridge-utils

  echo -e '# Load i40e drivers\ni40e' > /etc/modules-load.d/i40e.conf

  echo -e '# Load bonding drivers\nbonding' > /etc/modules-load.d/bonding.conf

  if [ -f "/etc/sysconfig/network-scripts/ifcfg-eth0" ]; then
    ln -s /etc/sysconfig/network-scripts/ifcfg-eth0 /etc/sysconfig/network-scripts/ifcfg-ens1f0
    ln -s /etc/sysconfig/network-scripts/ifcfg-eth0 /etc/sysconfig/network-scripts/ifcfg-p1p1
  fi

}

case ${DISTRO_ID} in
  centos|rhel)
    deploy_centos
    ;;
  ubuntu|debian)
    debian_deploy
    ;;
esac

